### PR TITLE
Multisite fix

### LINKED ISSUE #24: Bug: Multisite URL Rewriting Not Functional
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Subdomain-based multisite URLs aren't modified in any helpful way. The full current URL host-part is replaced by the stage's host-part, with no attempt made to preserve the blog's domain.

#### What have you tried?
Configured the `ENVIRONMENTS` array with the URLs of the "main site" or just the domain suffix.

#### What insights have you gained?
When originally implemented in https://github.com/roots/wp-stage-switcher/commit/890a7111273e553dcfda9329f57261dac331e1af, the host was split on the assumption that the subdomain would be only a single level, which worked in most cases, but not all. When rewritten in #7, Purl was used for its `registerableDomain` property to attempt to determine the base domain portion which should be replaced and the subdomain which should be kept. Finally, in #18, the Purl dependancy was removed, but the `multisite_url` method was simplified too much and all logic about trying to determine subdomain and base domain was removed.

#### Possible solutions
Without involving external dependancies (and even then, a solution may not be available for every possible outcome), determining with certainty the sub domain/base domain portion of a multisite URL is difficult. I propose moving back to a solution similar to the original in https://github.com/roots/wp-stage-switcher/commit/890a7111273e553dcfda9329f57261dac331e1af but also providing a filter to allow for domain structures that don't fit.

#### Temporary workarounds
The `ENVIRONMENTS` array can be defined in a `sunrise.php` drop-in once the multisite domain has been resolved, but this still presents an issue where URL scheme might be changed based on the scheme of the current stage (ie. a production site using the https scheme would overwrite an http scheme for a development URL creating a broken link).

### Steps To Reproduce

1. Set up a subdomain-based multisite installation in 2 or more environments
1. Configure the `ENVIRONMENTS` array with URLs for these environments

### Expected Behavior

Subdomain portions of the environment URL will be maintained while base environment domains are replaced

### Actual Behavior

The entire subdomain URL is replaced with the URL from the `ENVIRONMENTS` array, discarding the subdomain

### Relevant Log Output

_No response_

### Versions

2.1.1

### PR DESCRIPTION
**Pull request by dotsam**
Fixes #24 

I did end up taking the "treat the URL as a suffix" approach, rather than trying to guess and split the domain into parts. I believe this should handle all cases, but in cases where there isn't a match, it may produce an invalid URL.

As discussed, I've also added a filter for cases when the normal logic doesn't apply (primarily I'm thinking of production sites that have a unique domain, in which case the user will need to maintain their own mapping).

I've also removed the composer autoloader since there are no longer any external deps, and also tweaked the CSS selector for the admin bar icon to be more in-line with how WP Core targets things.

### CODE REVIEW

**Comment by dotsam** [comment]
@swalkinshaw Thoughts on this PR? I'm happily using it in production on a multisite subdomain installation.

File: wp-stage-switcher.php [hunk 1]
```diff
@@ -49,29 +48,29 @@ public function admin_bar_stage_switcher($admin_bar) {
...
-      $admin_bar->add_menu([
-        'id'     => 'environment',
-        'parent' => 'top-secondary',
-        'title'  => ucwords($current_stage),
-        'href'   => '#',
-        'meta'   => [
-          'class' => 'environment-' . sanitize_html_class(strtolower($current_stage)),
-        ],
-      ]);
+      $url = apply_filters('bedrock/stage_switcher_url', rtrim($url, '/') . $_SERVER['REQUEST_URI'], $url, $stage);
```
Comment (swalkinshaw) [inline wp-stage-switcher.php:73]: Should the filter name just be the plugin name exactly? So either `roots/wp-stage-switcher` or `wp-stage-switcher`. I don't think `bedrock` should be part of it?

Comment (dotsam) [reply wp-stage-switcher.php:73]: I was using the format of the existing `bedrock/stage_switcher_visibility` filter, but I'm happy to change it

Comment (swalkinshaw) [reply wp-stage-switcher.php:73]: Ah sorry, forgot about that. Okay this works 👍

**Comment by swalkinshaw** [comment]
Thanks @dotsam. We'll do a release soon

**Comment by dotsam** [comment]
@swalkinshaw Hi Scott, would it be possible to cut a new release now? I've had dev-master running on multisite and non-multisite installs for a while now without issue.

**Comment by retlehs** [comment]
@dotsam done, thank you for contributing!
